version: '3.8'

services:
  app:
    image: my-app:latest  # Use the myapp1:latest image
    ports:
      - "9091:9091"
    environment:
      - ENABLE_PROMETHEUS_METRICS=true

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
      
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
